### ISSUE TITLE
[FR] Banner widget?

### ISSUE THREAD

**Issue by jvonhoff** [gorootde/silverbullet-collection#10]
I was trying to recreate the [banner plugin from Logseq](https://github.com/yoyurec/logseq-banners-plugin), and while I made some progress, I think I'm missing a key piece.

```
---
description: Adds a Banner to tagged pages
banner: "https://media.torque.com.sg/public/2019/03/Bugatti-Chiron-front-exterior-4.jpg"
tags: template
hooks.top:
  where: 'true'
  order: 0
---
```template

![[{{@page.banner}}]]

!(banner)[{{@page.banner}}]

\```
```

This gives me a block at the top of every page that has some banner: metadata, but it doesn't render as a picture (see below), so I'm hoping to stir up enough interest to get some help.

![image](https://github.com/gorootde/silverbullet-collection/assets/8107932/bbf4fa38-a95c-4409-90a8-d129213e8d12)

**Comment by jvonhoff** [comment]
I guess I wasn't too far off...  If I actually use the correct syntax (URL goes in parentheses, not brackets) it kinda works!  It looks like the image sizing might not be working the way I thought it would, but it's a start!
![image](https://github.com/user-attachments/assets/1eb19f9d-1c5b-40d4-b4f4-271bd0d33b9a)

**Comment by gorootde** [comment]
Congrats for finding the solution on your own 👍  Would you like to contribute this as a template?

**Comment by jvonhoff** [comment]
> Would you like to contribute this as a template?

Definitely, if anyone else can use it... That's what keeps the open source world turning, right?

**Comment by gorootde** [comment]
Awesome, looking forward to your PR

**Comment by jvonhoff** [comment]
> Awesome, looking forward to your PR

It's there, but let me know if I need to tweak it!  Thanks again!
