### ISSUE TITLE
Contributions

### ISSUE THREAD

**Issue by malys** [gorootde/silverbullet-collection#13]
Hi,
To find easily your project, could you add these topics:
* awesome
* silverbullet
*  silverbullet-plugs
* ....

Moreover, I have created 2 plugs:
- https://github.com/malys/silverbullet-mindmap: support of mindmap
- https://github.com/LogeshG5/silverbullet-plantuml/

Thanks

**Comment by gorootde** [comment]
Thanks for pointing this out. I added some topics and your two plugs as well.
